/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel;

import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author Namit
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /** Creates new form NewJFrame4 */
    public NewJFrame4() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1366, 273);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Go Goa!");
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 320, 200, 37);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hyatt.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jInternalFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 410, 180, 210);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel10.setText("Hyatt Place, Candolim");
        jInternalFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 420, 340, 30);

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(1100, 570, 120, 40);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("jLabel11");
        jLabel11.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(660, 420, 2, 200);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("jLabel11");
        jLabel12.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(1060, 420, 2, 200);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Leela Collage.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jInternalFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(330, 440, 280, 160);

        jLabel14.setText("<html>\n<a href=\"www.google.com\">See on Maps</a>");
        jInternalFrame1.getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 590, 110, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Amenties");
        jInternalFrame1.getContentPane().add(jLabel15);
        jLabel15.setBounds(690, 430, 90, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("<html> <div># Wifi\t</div>\n<div># Conference rooms</div>\n<div># Pool</div>\n<div># Sports </div>\n<div># 24 hour service</div>  \n<div># King Size Beds</div>\n<div># Spa\t\t</div>\t    ");
        jInternalFrame1.getContentPane().add(jLabel16);
        jLabel16.setBounds(690, 470, 130, 140);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("<html>\n<div># Bathtub+Shower</div>\n<div># Gym\t\t</div>\t    \n<div># Satellite TV </div>\n<div># Hotel Bar\t</div>\t   \n<div> # Laundary Service </div>\n<div># Restaurant \t</div>\t    \n<div># A/C</div>");
        jInternalFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(900, 470, 130, 140);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 51, 51));
        jLabel28.setText("<html> <strike>Rs. 10030</strike>");
        jInternalFrame1.getContentPane().add(jLabel28);
        jLabel28.setBounds(1100, 690, 120, 26);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("<html> <strike>Rs. 7984</strike>");
        jInternalFrame1.getContentPane().add(jLabel29);
        jLabel29.setBounds(1100, 440, 110, 29);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 204, 0));
        jLabel30.setText("Rs. 8850");
        jInternalFrame1.getContentPane().add(jLabel30);
        jLabel30.setBounds(1100, 740, 120, 29);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 204, 0));
        jLabel31.setText("Rs. 7040");
        jInternalFrame1.getContentPane().add(jLabel31);
        jLabel31.setBounds(1100, 500, 110, 29);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 400, 1140, 230);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mayfair.jpg"))); // NOI18N
        jLabel18.setText("jLabel9");
        jInternalFrame1.getContentPane().add(jLabel18);
        jLabel18.setBounds(120, 650, 180, 210);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel19.setText("Mayfair Hideaway Resort");
        jInternalFrame1.getContentPane().add(jLabel19);
        jLabel19.setBounds(310, 660, 340, 30);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(1100, 810, 120, 40);

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("jLabel11");
        jLabel20.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel20);
        jLabel20.setBounds(660, 660, 2, 200);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("jLabel11");
        jLabel21.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel21);
        jLabel21.setBounds(1060, 660, 2, 200);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shangri-la Collage.jpg"))); // NOI18N
        jLabel22.setText("jLabel13");
        jInternalFrame1.getContentPane().add(jLabel22);
        jLabel22.setBounds(330, 680, 280, 160);

        jLabel23.setText("<html>\n<a href=\"www.google.com\">See on Maps</a>");
        jInternalFrame1.getContentPane().add(jLabel23);
        jLabel23.setBounds(340, 830, 110, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Amenties");
        jInternalFrame1.getContentPane().add(jLabel24);
        jLabel24.setBounds(690, 670, 90, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("<html> <div># Wifi\t</div>\n<div># Conference rooms</div>\n<div># Pool</div>\n<div># Sports </div>\n<div># 24 hour service</div>  \n<div># King Size Beds</div>\n<div># Spa\t\t</div>\t    ");
        jInternalFrame1.getContentPane().add(jLabel25);
        jLabel25.setBounds(690, 710, 130, 140);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("<html>\n<div># Bathtub+Shower</div>\n<div># Gym\t\t</div>\t    \n<div># Satellite TV </div>\n<div># Hotel Bar\t</div>\t   \n<div> # Laundary Service </div>\n<div># Restaurant \t</div>\t    \n<div># A/C</div>");
        jInternalFrame1.getContentPane().add(jLabel26);
        jLabel26.setBounds(900, 710, 130, 140);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel27);
        jLabel27.setBounds(110, 640, 1140, 230);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 51, 51));
        jLabel32.setText("<html> <strike>Rs. 17425</strike>");
        jInternalFrame1.getContentPane().add(jLabel32);
        jLabel32.setBounds(1100, 930, 120, 26);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 204, 0));
        jLabel33.setText("Rs. 14720");
        jInternalFrame1.getContentPane().add(jLabel33);
        jLabel33.setBounds(1100, 980, 120, 29);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Leela Goa.jpg"))); // NOI18N
        jLabel34.setText("jLabel9");
        jInternalFrame1.getContentPane().add(jLabel34);
        jLabel34.setBounds(120, 890, 180, 210);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel35.setText("The Leela, Goa");
        jInternalFrame1.getContentPane().add(jLabel35);
        jLabel35.setBounds(310, 900, 340, 30);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(1100, 1050, 120, 40);

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("jLabel11");
        jLabel36.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel36);
        jLabel36.setBounds(660, 900, 2, 200);

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("jLabel11");
        jLabel37.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel37);
        jLabel37.setBounds(1060, 900, 2, 200);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lalit Collage.jpg"))); // NOI18N
        jLabel38.setText("jLabel13");
        jInternalFrame1.getContentPane().add(jLabel38);
        jLabel38.setBounds(330, 920, 280, 160);

        jLabel39.setText("<html>\n<a href=\"www.google.com\">See on Maps</a>");
        jInternalFrame1.getContentPane().add(jLabel39);
        jLabel39.setBounds(340, 1070, 110, 20);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("Amenties");
        jInternalFrame1.getContentPane().add(jLabel40);
        jLabel40.setBounds(690, 910, 90, 20);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("<html> <div># Wifi\t</div>\n<div># Conference rooms</div>\n<div># Pool</div>\n<div># Sports </div>\n<div># 24 hour service</div>  \n<div># King Size Beds</div>\n<div># Spa\t\t</div>\t    ");
        jInternalFrame1.getContentPane().add(jLabel41);
        jLabel41.setBounds(690, 950, 130, 140);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("<html>\n<div># Bathtub+Shower</div>\n<div># Gym\t\t</div>\t    \n<div># Satellite TV </div>\n<div># Hotel Bar\t</div>\t   \n<div> # Laundary Service </div>\n<div># Restaurant \t</div>\t    \n<div># A/C</div>");
        jInternalFrame1.getContentPane().add(jLabel42);
        jLabel42.setBounds(900, 950, 130, 140);

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel43);
        jLabel43.setBounds(110, 880, 1140, 230);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 51, 51));
        jLabel44.setText("<html> <strike>Rs. 10238</strike>");
        jInternalFrame1.getContentPane().add(jLabel44);
        jLabel44.setBounds(1100, 1170, 120, 26);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 204, 0));
        jLabel45.setText("Rs. 9178");
        jInternalFrame1.getContentPane().add(jLabel45);
        jLabel45.setBounds(1100, 1220, 120, 29);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Novatel.jpg"))); // NOI18N
        jLabel46.setText("jLabel9");
        jInternalFrame1.getContentPane().add(jLabel46);
        jLabel46.setBounds(120, 1130, 180, 210);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel47.setText("Novotel Goa Resort");
        jInternalFrame1.getContentPane().add(jLabel47);
        jLabel47.setBounds(310, 1140, 340, 30);

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Book");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(1100, 1290, 120, 40);

        jLabel48.setBackground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("jLabel11");
        jLabel48.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel48);
        jLabel48.setBounds(660, 1140, 2, 200);

        jLabel49.setBackground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("jLabel11");
        jLabel49.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel49);
        jLabel49.setBounds(1060, 1140, 2, 200);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ashoka Collage.jpg"))); // NOI18N
        jLabel50.setText("jLabel13");
        jInternalFrame1.getContentPane().add(jLabel50);
        jLabel50.setBounds(330, 1160, 280, 160);

        jLabel51.setText("<html>\n<a href=\"www.google.com\">See on Maps</a>");
        jInternalFrame1.getContentPane().add(jLabel51);
        jLabel51.setBounds(340, 1310, 110, 20);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setText("Amenties");
        jInternalFrame1.getContentPane().add(jLabel52);
        jLabel52.setBounds(690, 1150, 90, 20);

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setText("<html> <div># Wifi\t</div>\n<div># Conference rooms</div>\n<div># Pool</div>\n<div># Sports </div>\n<div># 24 hour service</div>  \n<div># King Size Beds</div>\n<div># Spa\t\t</div>\t    ");
        jInternalFrame1.getContentPane().add(jLabel53);
        jLabel53.setBounds(690, 1190, 130, 140);

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("<html>\n<div># Bathtub+Shower</div>\n<div># Gym\t\t</div>\t    \n<div># Satellite TV </div>\n<div># Hotel Bar\t</div>\t   \n<div> # Laundary Service </div>\n<div># Restaurant \t</div>\t    \n<div># A/C</div>");
        jInternalFrame1.getContentPane().add(jLabel54);
        jLabel54.setBounds(900, 1190, 130, 140);

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel55);
        jLabel55.setBounds(110, 1120, 1140, 230);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 51, 51));
        jLabel56.setText("<html> <strike>Rs. 19147</strike>");
        jInternalFrame1.getContentPane().add(jLabel56);
        jLabel56.setBounds(1100, 1170, 120, 26);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shangri-la Collage.jpg"))); // NOI18N
        jLabel57.setText("jLabel13");
        jInternalFrame1.getContentPane().add(jLabel57);
        jLabel57.setBounds(330, 1160, 280, 160);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel58.setText("Shangri-La's - EROS Hotel");
        jInternalFrame1.getContentPane().add(jLabel58);
        jLabel58.setBounds(310, 1140, 340, 30);

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Book");
        jInternalFrame1.getContentPane().add(jButton6);
        jButton6.setBounds(1100, 1290, 120, 40);

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel59.setText("<html>\n<div># Bathtub+Shower</div>\n<div># Gym\t\t</div>\t    \n<div># Satellite TV </div>\n<div># Hotel Bar\t</div>\t   \n<div> # Laundary Service </div>\n<div># Restaurant \t</div>\t    \n<div># A/C</div>");
        jInternalFrame1.getContentPane().add(jLabel59);
        jLabel59.setBounds(900, 1190, 130, 140);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(51, 204, 0));
        jLabel60.setText("Rs. 17232");
        jInternalFrame1.getContentPane().add(jLabel60);
        jLabel60.setBounds(1100, 1220, 120, 29);

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel61.setText("<html> <div># Wifi\t</div>\n<div># Conference rooms</div>\n<div># Pool</div>\n<div># Sports </div>\n<div># 24 hour service</div>  \n<div># King Size Beds</div>\n<div># Spa\t\t</div>\t    ");
        jInternalFrame1.getContentPane().add(jLabel61);
        jLabel61.setBounds(690, 1190, 130, 140);

        jLabel62.setBackground(new java.awt.Color(255, 255, 255));
        jLabel62.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel62);
        jLabel62.setBounds(110, 1120, 1140, 230);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shangri-la.jpg"))); // NOI18N
        jLabel63.setText("jLabel9");
        jInternalFrame1.getContentPane().add(jLabel63);
        jLabel63.setBounds(120, 1130, 180, 210);

        jLabel64.setBackground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("jLabel11");
        jLabel64.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel64);
        jLabel64.setBounds(660, 1140, 2, 200);

        jLabel65.setText("<html>\n<a href=\"www.google.com\">See on Maps</a>");
        jInternalFrame1.getContentPane().add(jLabel65);
        jLabel65.setBounds(340, 1310, 110, 20);

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setText("Amenties");
        jInternalFrame1.getContentPane().add(jLabel66);
        jLabel66.setBounds(690, 1150, 90, 20);

        jLabel67.setBackground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("jLabel11");
        jLabel67.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel67);
        jLabel67.setBounds(1060, 1140, 2, 200);

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 51, 51));
        jLabel68.setText("<html> <strike>Rs. 12086</strike>");
        jInternalFrame1.getContentPane().add(jLabel68);
        jLabel68.setBounds(1100, 1410, 120, 26);

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(51, 204, 0));
        jLabel69.setText("Rs. 8496");
        jInternalFrame1.getContentPane().add(jLabel69);
        jLabel69.setBounds(1100, 1460, 120, 29);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kenilworth.jpg"))); // NOI18N
        jLabel70.setText("jLabel9");
        jInternalFrame1.getContentPane().add(jLabel70);
        jLabel70.setBounds(120, 1370, 180, 210);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel71.setText("Kenilworth Beach Resort");
        jInternalFrame1.getContentPane().add(jLabel71);
        jLabel71.setBounds(310, 1380, 340, 30);

        jButton7.setBackground(new java.awt.Color(0, 153, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Book");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton7);
        jButton7.setBounds(1100, 1530, 120, 40);

        jLabel72.setBackground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("jLabel11");
        jLabel72.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel72);
        jLabel72.setBounds(660, 1380, 2, 200);

        jLabel73.setBackground(new java.awt.Color(0, 0, 0));
        jLabel73.setText("jLabel11");
        jLabel73.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel73);
        jLabel73.setBounds(1060, 1380, 2, 200);

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Le Collage.jpg"))); // NOI18N
        jLabel74.setText("jLabel13");
        jInternalFrame1.getContentPane().add(jLabel74);
        jLabel74.setBounds(330, 1400, 280, 160);

        jLabel75.setText("<html>\n<a href=\"www.google.com\">See on Maps</a>");
        jInternalFrame1.getContentPane().add(jLabel75);
        jLabel75.setBounds(340, 1550, 110, 20);

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel76.setText("Amenties");
        jInternalFrame1.getContentPane().add(jLabel76);
        jLabel76.setBounds(690, 1390, 90, 20);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel77.setText("<html> <div># Wifi\t</div>\n<div># Conference rooms</div>\n<div># Pool</div>\n<div># Sports </div>\n<div># 24 hour service</div>  \n<div># King Size Beds</div>\n<div># Spa\t\t</div>\t    ");
        jInternalFrame1.getContentPane().add(jLabel77);
        jLabel77.setBounds(690, 1430, 130, 140);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel78.setText("<html>\n<div># Bathtub+Shower</div>\n<div># Gym\t\t</div>\t    \n<div># Satellite TV </div>\n<div># Hotel Bar\t</div>\t   \n<div> # Laundary Service </div>\n<div># Restaurant \t</div>\t    \n<div># A/C</div>");
        jInternalFrame1.getContentPane().add(jLabel78);
        jLabel78.setBounds(900, 1430, 130, 140);

        jLabel79.setBackground(new java.awt.Color(255, 255, 255));
        jLabel79.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel79);
        jLabel79.setBounds(110, 1360, 1140, 230);

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 51, 51));
        jLabel80.setText("<html> <strike>Rs. 19147</strike>");
        jInternalFrame1.getContentPane().add(jLabel80);
        jLabel80.setBounds(1100, 1410, 120, 26);

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shangri-la Collage.jpg"))); // NOI18N
        jLabel81.setText("jLabel13");
        jInternalFrame1.getContentPane().add(jLabel81);
        jLabel81.setBounds(330, 1400, 280, 160);

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel82.setText("Shangri-La's - EROS Hotel");
        jInternalFrame1.getContentPane().add(jLabel82);
        jLabel82.setBounds(310, 1380, 340, 30);

        jButton8.setBackground(new java.awt.Color(0, 153, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Book");
        jInternalFrame1.getContentPane().add(jButton8);
        jButton8.setBounds(1100, 1530, 120, 40);

        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel83.setText("<html>\n<div># Bathtub+Shower</div>\n<div># Gym\t\t</div>\t    \n<div># Satellite TV </div>\n<div># Hotel Bar\t</div>\t   \n<div> # Laundary Service </div>\n<div># Restaurant \t</div>\t    \n<div># A/C</div>");
        jInternalFrame1.getContentPane().add(jLabel83);
        jLabel83.setBounds(900, 1430, 130, 140);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(51, 204, 0));
        jLabel84.setText("Rs. 17232");
        jInternalFrame1.getContentPane().add(jLabel84);
        jLabel84.setBounds(1100, 1460, 120, 29);

        jLabel85.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel85.setText("<html> <div># Wifi\t</div>\n<div># Conference rooms</div>\n<div># Pool</div>\n<div># Sports </div>\n<div># 24 hour service</div>  \n<div># King Size Beds</div>\n<div># Spa\t\t</div>\t    ");
        jInternalFrame1.getContentPane().add(jLabel85);
        jLabel85.setBounds(690, 1430, 130, 140);

        jLabel86.setBackground(new java.awt.Color(255, 255, 255));
        jLabel86.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel86);
        jLabel86.setBounds(110, 1360, 1140, 230);

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shangri-la.jpg"))); // NOI18N
        jLabel87.setText("jLabel9");
        jInternalFrame1.getContentPane().add(jLabel87);
        jLabel87.setBounds(120, 1370, 180, 210);

        jLabel88.setBackground(new java.awt.Color(0, 0, 0));
        jLabel88.setText("jLabel11");
        jLabel88.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel88);
        jLabel88.setBounds(660, 1380, 2, 200);

        jLabel89.setText("<html>\n<a href=\"www.google.com\">See on Maps</a>");
        jInternalFrame1.getContentPane().add(jLabel89);
        jLabel89.setBounds(340, 1550, 110, 20);

        jLabel90.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel90.setText("Amenties");
        jInternalFrame1.getContentPane().add(jLabel90);
        jLabel90.setBounds(690, 1390, 90, 20);

        jLabel91.setBackground(new java.awt.Color(0, 0, 0));
        jLabel91.setText("jLabel11");
        jLabel91.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel91);
        jLabel91.setBounds(1060, 1380, 2, 200);

        jLabel93.setBackground(new java.awt.Color(0, 0, 0));
        jLabel93.setFont(new java.awt.Font("Papyrus", 1, 30)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("<html> <center>Savings Karo<br>TravelGo Karo</center>");
        jLabel93.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel93);
        jLabel93.setBounds(560, 1660, 250, 120);

        jLabel94.setBackground(new java.awt.Color(0, 0, 0));
        jLabel94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("<html>\nAn initiative by<br>\nNamit & Gaurav");
        jLabel94.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel94);
        jLabel94.setBounds(160, 1730, 130, 40);

        jLabel95.setBackground(new java.awt.Color(0, 0, 0));
        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("Contact:");
        jLabel95.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel95);
        jLabel95.setBounds(980, 1660, 230, 60);

        jLabel96.setBackground(new java.awt.Color(0, 0, 0));
        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("<html>+918375048094<br>+918860440405");
        jLabel96.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel96);
        jLabel96.setBounds(990, 1730, 140, 40);

        jLabel97.setBackground(new java.awt.Color(0, 0, 0));
        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("TravelGo");
        jLabel97.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel97);
        jLabel97.setBounds(150, 1660, 230, 60);

        jLabel92.setBackground(new java.awt.Color(0, 0, 0));
        jLabel92.setText("jLabel92");
        jLabel92.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel92);
        jLabel92.setBounds(-10, 1650, 1380, 170);

        jLabel98.setBackground(new java.awt.Color(255, 102, 102));
        jLabel98.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel98);
        jLabel98.setBounds(100, 384, 1160, 1220);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int price;
    static String hname;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NewJFrame obj=new NewJFrame();
        price=(obj.ndays)*7040;
        hname = jLabel10.getText();
        NewJFrame3 obj1=new NewJFrame3();
        obj1.setVisible(true);
        obj1.setExtendedState(MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NewJFrame obj=new NewJFrame();
        price=(obj.ndays)*8850;
        hname = jLabel19.getText();
        NewJFrame3 obj1=new NewJFrame3();
        obj1.setVisible(true);
        obj1.setExtendedState(MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        NewJFrame obj=new NewJFrame();
        price=(obj.ndays)*14720;
        hname = jLabel35.getText();
        NewJFrame3 obj1=new NewJFrame3();
        obj1.setVisible(true);
        obj1.setExtendedState(MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        NewJFrame obj=new NewJFrame();
        price=(obj.ndays)*9178;
        hname = jLabel47.getText();
        NewJFrame3 obj1=new NewJFrame3();
        obj1.setVisible(true);
        obj1.setExtendedState(MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        NewJFrame obj=new NewJFrame();
        price=(obj.ndays)*8496;
        hname = jLabel71.getText();
        NewJFrame3 obj1=new NewJFrame3();
        obj1.setVisible(true);
        obj1.setExtendedState(MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame4 obj=new NewJFrame4();
                obj.setVisible(true);
                obj.setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
