/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

/**
 *
 * @author Namit
 */
public class NewJFrame7 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame7
     */
    public NewJFrame7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        custom = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 1050));

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel93.setBackground(new java.awt.Color(0, 0, 0));
        jLabel93.setFont(new java.awt.Font("Papyrus", 1, 30)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("<html> <center>Savings Karo<br>TravelGo Karo</center>");
        jLabel93.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel93);
        jLabel93.setBounds(560, 890, 250, 120);

        jLabel94.setBackground(new java.awt.Color(0, 0, 0));
        jLabel94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("<html>\nAn initiative by<br>\nNamit & Gaurav");
        jLabel94.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel94);
        jLabel94.setBounds(160, 960, 130, 40);

        jLabel95.setBackground(new java.awt.Color(0, 0, 0));
        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("Contact:");
        jLabel95.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel95);
        jLabel95.setBounds(980, 890, 230, 60);

        jLabel96.setBackground(new java.awt.Color(0, 0, 0));
        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("<html>+918375048094<br>+918860440405");
        jLabel96.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel96);
        jLabel96.setBounds(990, 960, 140, 40);

        jLabel97.setBackground(new java.awt.Color(0, 0, 0));
        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("TravelGo");
        jLabel97.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel97);
        jLabel97.setBounds(150, 890, 230, 60);

        jLabel92.setBackground(new java.awt.Color(0, 0, 0));
        jLabel92.setText("jLabel92");
        jLabel92.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel92);
        jLabel92.setBounds(0, 880, 1380, 170);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1366, 273);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hotel :");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 480, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Check-in Date:");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 530, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Check-out Date:");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 580, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Amount:");
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 630, 90, 30);

        custom.setBackground(new java.awt.Color(255, 255, 255));
        custom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        custom.setOpaque(true);
        jInternalFrame1.getContentPane().add(custom);
        custom.setBounds(460, 340, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("<html>Congratulations Mr./Ms.                                 <br><br>you've successfully booked your hotel and the final details are as follows :</html>");
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 340, 690, 70);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Payement will be made at the time of check-in ");
        jInternalFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 740, 580, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Enjoy your stay....");
        jInternalFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 780, 230, 30);

        h1.setBackground(new java.awt.Color(255, 255, 255));
        h1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h1.setOpaque(true);
        jInternalFrame1.getContentPane().add(h1);
        h1.setBounds(450, 480, 320, 30);

        h2.setBackground(new java.awt.Color(255, 255, 255));
        h2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h2.setOpaque(true);
        jInternalFrame1.getContentPane().add(h2);
        h2.setBounds(790, 480, 100, 30);

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c1.setOpaque(true);
        jInternalFrame1.getContentPane().add(c1);
        c1.setBounds(450, 530, 440, 30);

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c2.setOpaque(true);
        jInternalFrame1.getContentPane().add(c2);
        c2.setBounds(450, 580, 440, 30);

        t2.setBackground(new java.awt.Color(255, 255, 255));
        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.setOpaque(true);
        jInternalFrame1.getContentPane().add(t2);
        t2.setBounds(470, 630, 420, 30);

        t1.setBackground(new java.awt.Color(255, 255, 255));
        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.setText("Rs.");
        t1.setOpaque(true);
        jInternalFrame1.getContentPane().add(t1);
        t1.setBounds(450, 630, 20, 30);

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 430, 640, 280);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 310, 800, 540);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(70, 470, 100, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Please Confirm to get final booking details.");
        jInternalFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 530, 240, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        NewJFrame obj=new NewJFrame();
        NewJFrame1 obj1=new NewJFrame1();
        NewJFrame5 obj5=new NewJFrame5();
        NewJFrame4 obj4=new NewJFrame4();
        NewJFrame3 obj3=new NewJFrame3();
        c1.setText(obj.cin);
        c2.setText(obj.cout);
        custom.setText(obj3.user);
        if(obj.city==0){
            h2.setText("New Delhi");
            h1.setText(obj1.hname);
            t2.setText(String.valueOf(obj1.price));
        }
        else if(obj.city==1){
            h2.setText("Goa");
            h1.setText(obj4.hname);
            t2.setText(String.valueOf(obj4.price));
        }
        else if(obj.city==2){
            h2.setText("Mumbai");
            h1.setText(obj5.hname);
            t2.setText(String.valueOf(obj5.price));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel custom;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    // End of variables declaration//GEN-END:variables
}
