/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Namit
 */
public class NewJFrame6 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame6
     */
    public NewJFrame6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        first1 = new javax.swing.JLabel();
        first2 = new javax.swing.JLabel();
        first3 = new javax.swing.JLabel();
        first4 = new javax.swing.JLabel();
        first5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        join = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        first = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1356, 1051));

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        first1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first1.setText("E-mail Address:");
        jInternalFrame1.getContentPane().add(first1);
        first1.setBounds(480, 540, 100, 30);

        first2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first2.setText("Password:");
        jInternalFrame1.getContentPane().add(first2);
        first2.setBounds(480, 660, 70, 30);

        first3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first3.setText("First Name:");
        jInternalFrame1.getContentPane().add(first3);
        first3.setBounds(480, 420, 70, 30);

        first4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first4.setText("First Name:");
        jInternalFrame1.getContentPane().add(first4);
        first4.setBounds(480, 420, 70, 30);

        first5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first5.setText("Mobile No.:");
        jInternalFrame1.getContentPane().add(first5);
        first5.setBounds(480, 600, 70, 30);

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(600, 660, 270, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(640, 730, 90, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(600, 420, 270, 30);

        jLabel97.setBackground(new java.awt.Color(0, 0, 0));
        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("TravelGo");
        jLabel97.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel97);
        jLabel97.setBounds(150, 860, 230, 60);

        jLabel95.setBackground(new java.awt.Color(0, 0, 0));
        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("Contact:");
        jLabel95.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel95);
        jLabel95.setBounds(980, 860, 230, 60);

        join.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        join.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        join.setText("Join TravelGo");
        jInternalFrame1.getContentPane().add(join);
        join.setBounds(620, 360, 130, 30);

        jLabel94.setBackground(new java.awt.Color(0, 0, 0));
        jLabel94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("<html>\nAn initiative by<br>\nNamit & Gaurav");
        jLabel94.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel94);
        jLabel94.setBounds(160, 930, 130, 40);

        jLabel93.setBackground(new java.awt.Color(0, 0, 0));
        jLabel93.setFont(new java.awt.Font("Papyrus", 1, 30)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("<html> <center>Savings Karo<br>TravelGo Karo</center>");
        jLabel93.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel93);
        jLabel93.setBounds(560, 860, 250, 120);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1366, 273);

        jLabel96.setBackground(new java.awt.Color(0, 0, 0));
        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("<html>+918375048094<br>+918860440405");
        jLabel96.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel96);
        jLabel96.setBounds(990, 930, 140, 40);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(jTextField4);
        jTextField4.setBounds(600, 600, 270, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(jTextField3);
        jTextField3.setBounds(600, 540, 270, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(jTextField2);
        jTextField2.setBounds(600, 480, 270, 30);

        first.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first.setText("Last Name:");
        jInternalFrame1.getContentPane().add(first);
        first.setBounds(480, 480, 70, 30);

        jLabel92.setBackground(new java.awt.Color(0, 0, 0));
        jLabel92.setText("jLabel92");
        jLabel92.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel92);
        jLabel92.setBounds(0, 850, 1380, 170);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 330, 610, 470);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection con=null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","system");
            String fname=jTextField1.getText();
            String lname=jTextField2.getText();
            String email=jTextField3.getText();
            String phn=jTextField4.getText();
            String pass=jPasswordField2.getText();
            PreparedStatement pst=con.prepareStatement("insert into travelgo values(?,?,?,?,?)");
            pst.setString(1, fname);
            pst.setString(2, lname);
            pst.setString(3, email);
            pst.setString(4, phn);
            pst.setString(5, pass);
            int rt=pst.executeUpdate();
            if(rt>0){
		JOptionPane.showMessageDialog(this, "Success");
                NewJFrame3 obj1=new NewJFrame3();
                obj1.setVisible(true);
                obj1.setExtendedState(MAXIMIZED_BOTH);
                this.dispose();
            }
            else{
		JOptionPane.showMessageDialog(this, "Failure");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame6 obj=new NewJFrame6();
                obj.setVisible(true);
                obj.setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel first;
    private javax.swing.JLabel first1;
    private javax.swing.JLabel first2;
    private javax.swing.JLabel first3;
    private javax.swing.JLabel first4;
    private javax.swing.JLabel first5;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel join;
    // End of variables declaration//GEN-END:variables
}
